IDLE_TIMEOUT:
  600000
MAXIMUM_POOL_SIZE:
  40
MINIMUM_IDLE:
  5
DriverClassName:
  oracle.jdbc.driver.OracleDriver
DB_URL:
  jdbc:oracle:thin:@10.22.19.193:1521:VNPTEST
DB_USERNAME:
  smsgw
DB_PASSWORD:
  smsgw